packages:
  - docs
  - 'packages/*'
catalog:
  vue: ^3.5.13
  '@fortawesome/fontawesome-free': ^6.7.2
  '@fortawesome/fontawesome-svg-core': ^6.7.2
  '@fortawesome/free-solid-svg-icons': ^6.7.2
  '@fortawesome/vue-fontawesome': ^3.0.8
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
